name: buildx

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: lustyn/magicdrive

jobs:
  buildx:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Get Variables
        id: vars
        run: |
          VER_FULL=${GITHUB_REF#refs/*/}
          echo ::set-output name=VER_FULL::${VER_FULL}
          echo ::set-output name=VER_MINOR::$(echo $VER_FULL | cut -d. -f-2)
          echo ::set-output name=VER_MAJOR::$(echo $VER_FULL | cut -d. -f-1)
      -
        name: Buildx and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.VER_FULL }}
            ghcr.io/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.VER_MINOR }}
            ghcr.io/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.VER_MAJOR }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: |
            magicdrive `${{ steps.vars.outputs.VER_FULL }}`
            `ghcr.io/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.VER_FULL }}`