#!/usr/bin/with-contenv bash
. /usr/local/bin/variables

echo "*** checking plexdrive config"
while [ ! -f "${pd_config}" ] || [ ! -f "${pd_token}" ]; do
    echo "Waiting for plexdrive config files in ${config_dir}. Retrying in 30s ..."
    echo "RUN: docker exec -it <CONTAINER_NAME> plexdrive_setup"
    sleep 30
done

echo "*** checking rclone config"
while [ ! -f "${rclone_config}" ]; do
    echo "Waiting for rclone config file in ${rclone_config}. Retrying in 30s ..."
    echo "RUN: docker exec -it <CONTAINER_NAME> rclone_setup"
    sleep 30
done

check_mountpoint() {
    echo "*** checking mountpoint: ${pd_mountpoint}"
    while findmnt "${1}" | grep -q fuse; do
        echo "ERROR: mountpoint (${1}) already mounted"
        fusermount -uz "${1}"
        echo "Retrying in 15s ..."
        sleep 15
    done
}

check_mountpoint "${mfs_mountpoint}"
check_mountpoint "${rclone_mountpoint}"
check_mountpoint "${pd_mountpoint}"

# permissions
chown -R abc:abc \
    ${config_dir} ${pd_mountpoint} ${rclone_mountpoint} ${mfs_mountpoint} /cache
chown abc:abc /local

# display version
echo "*** plexdrive $(plexdrive --version) ready!"
echo "*** rclone $(rclone --version) ready!"
echo "*** mergerfs $(mergerfs --version) ready!"
